-- The CREATE DATABASE statement is used to create a new SQL database.
USE favoriteThings;
--The INSERT INTO statement is used here to insert rows into the names table in the order I specifiy in THIS STATEMENT BELOW
INSERT INTO names (first_name, last_name, name_id)
VALUES 
('Moriah', 'Kincheloe', 1),
('Geovonni', 'Banano', 2),
('Michael', 'Corleone', 3),
('Rusty', 'Bohnsteil', 4),
('Shayla', 'Griffin', 5),
('Peter', 'Luchese', 6),
('Jada', 'Gambino', 7),
('Fredo', 'Rodolfo', 8),
('Lori', 'Monk', 9),
('Fred', 'Monk', 10),
('Penny', 'Gracie', 11),
('Luna', 'Jane', 12),
('Steven', 'Griffin', 13),
('Leslee', 'Jones', 14),
('Steven', 'Jones', 15),
('Dwyane', 'Wade', 16),
('Jesse', 'Stanley', 17),
('Michael', 'Jordan', 18),
('Hanh', 'Vu', 19),
('Margo', 'Mendez', 20),
('Moriah', 'Jones', 21),
('Heathcliffe', 'Ledger', 22),
('Joaquim', 'Phoenix', 23),
('Victor', 'Oladipo', 24),
('Reggie', 'Miller', 25),
('George', 'Ferguson', 26),
('Nicholas', 'Nakashima', 27),
('Steph', 'Bobbin', 28),
('Craig', 'Bobbin', 29),
('Wladymir', 'Klitscko', 30),
('Theodore', 'Decker', 31),
('Holden', 'Caulfield', 32),
('Jay', 'Gatsby', 33),
('Thomas', 'Tandy', 34),
('Phillip', 'Gise', 35),
('Brad', 'Marchand', 36),
('Walter', 'Payton', 37),
('Cooper', 'Williams', 38),
('Travis', 'Benson', 39),
('Patrice', 'Bergeron', 40),
('Zdeno', 'Chara', 41),
('Lee', 'Emmerson', 42),
('Dan', 'Henderson', 43),
('Vito', 'Corleone', 44),
('Calvin', 'Johnson', 45),
('Tim', 'Horton', 46),
('Bart', 'Simpson', 47),
('Zdeno', 'Chara', 48),
('Lee', 'Emmerson', 49),
('Lee', 'Emmerson', 50);--the VALUES inserted into the table